return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "dockerfile",
      "json",
      "yaml",
      "toml",
      "just",
      "regex",
      "vim",
      "lua",
      "markdown",
      "sql",
      "javascript",
      "typescript",
      "tsx",
      "rust",
      "cairo",
      "svelte",
      "go",
      "gomod",
      "gosum",
    },
  },
}
